<?php 
/////////////////////////////////////////////
/// Edgardo Pinto-Escalier
/// Project name - Cleaning Status
/// File name: formTokens.class.php
/////////////////////////////////////////////

//This class will generate tokens to help us deal with
//Cross-Site Request Forgery (CSRF). Source link: https://www.owasp.org/index.php/Cross-Site_Request_Forgery_(CSRF)

//We start by defining the formTokens class.
class formTokens {
	//Next we create the static method to generate the new tokens.
	//Here what we do is to bind a token with a session.
	public static function generateNewToken() {
		return userSessions::sessionValue(config::getPath('session/tokens_name'), md5(uniqid()));
	}

	//Next we create the public static method verifyToken.
	//With this method we will verify if the token exist in the session.
	public static function verifyToken($tokens) {
		$tokensName = config::getPath('session/tokens_name');
		//If there is a session with the token name defined in config,
		//and this tokem matches the one generated by the user then,
		if(userSessions::sessionIsThere($tokensName) && $tokens === userSessions::getSessionName($tokensName)) {
			//We delete the token here and return true.
			userSessions::deleteSession($tokensName);
			return true;
		}
		return false;
	}
}